steps:
- id: "tf init"
  name: "broadinstitute/terraform"
  entrypoint: "terraform/scripts/terraform.sh"
  args: ["init"]

- id: "tf apply"
  name: "broadinstitute/terraform"
  entrypoint: "terraform/scripts/terraform.sh"
  args: ["apply"]

options:
  env:
    - "TF_VAR_project_id=$PROJECT_ID"
    - "TF_VAR_credentials=/workspace/credentials.json"
    - "BRANCH_NAME=$BRANCH_NAME"
  secretEnv: ["GOOGLE_CREDENTIALS"]
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/terraform_sa_credentials/versions/latest
      env: GOOGLE_CREDENTIALS
